SimpleUserSession/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('session-app/', include('session_app.urls')),
    path('', lambda _: redirect("session_app:home")),
]

session_app/urls.py
from django.urls import path

from . import views

app_name = 'session_app'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

session_app/models.py
from django.db import models


class SiteUser(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=16,
                                unique=True)
    email = models.EmailField(max_length=128,
                              unique=True)
    password = models.CharField(max_length=256)

    def __str__(self):
        return self.username

    def to_json(self):
        return {
            'name': self.name,
            'username': self.username,
            'email': self.email,
        }

session_app/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View

from utils.decorators import handle_exception
from utils.utils import sha256_string

from .db_query import get_user_by_username, validate_user_password
from .models import SiteUser
from .session_manager import (add_user_to_session, get_user_in_session,
                              remove_session_user)


class HomeView(View):
    @handle_exception
    def get(self, request):
        user = get_user_in_session(request)
        user_name = user.name if user else ''
        return render(
            request,
            template_name="home.html",
            context={
                'user_name': user_name,
            }
        )


class RegisterView(View):
    @handle_exception
    def get(self, request):
        return render(
            request,
            'register.html',
        )

    @handle_exception
    def post(self, request):
        """
        DO NOT IMPLEMENT username unique check and email unique check!
        """

        data = request.POST

        name = data.get('name')
        username = data.get('username')
        email = data.get('email')
        password = data.get('password')

        password_hashed = sha256_string(password)

        user = SiteUser.objects.create(
            name=name,
            username=username,
            email=email,
            password=password_hashed,
        )

        return JsonResponse({
            "message": "ok",
        })


class LoginView(View):
    @handle_exception
    def get(self, request):
        return render(
            request,
            'login.html',
        )

    @handle_exception
    def post(self, request):

        data = request.POST

        username_or_email = data.get('usernameOrEmail')
        password = data.get('password')

        password_hashed = sha256_string(password)

        user = get_user_by_username(username_or_email)
        validate_user_password(user, password_hashed)

        add_user_to_session(request, user)

        return JsonResponse({
            "message": "ok",
        })


class LogoutView(View):
    @handle_exception
    def get(self, request):

        remove_session_user(request)

        return JsonResponse({
            "message": "ok",
        })

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'session_app:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'session_app:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'session_app:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'session_app:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid mt-3">
        {% block body %}
        {% endblock %}
    </div>

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block body %}
<h1>Welcome {{user_name}}</h1>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <div>
        <label for="id_username_or_email">Username/Email:</label>
        <input name="usernameOrEmail" id="id_username_or_email" placeholder="Enter username or Email" required>
    </div>
    <div>
        <label for="id_password">Password:</label>
        <input name="password" id="id_password" placeholder="Enter password" required>
    </div>
    <button type="submit">Login</button>
</form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <div>
        <label for="id_name">Name:</label>
        <input name="name" id="id_name" placeholder="Enter Name" required>
    </div>
    <div>
        <label for="id_username">Username:</label>
        <input name="username" id="id_username" placeholder="Enter username" required>
    </div>
    <div>
        <label for="id_email">Email:</label>
        <input name="email" id="id_email" placeholder="Enter email" required>
    </div>
    <div>
        <label for="id_password">Password:</label>
        <input name="password" id="id_password" placeholder="Enter password" required>
    </div>
    <button type="submit">Register</button>
</form>
{% endblock %}